import json
nb = json.load(open('eda.ipynb', 'r', encoding='utf-8'))
total = len(nb['cells'])
code_cells = sum(1 for c in nb['cells'] if c['cell_type'] == 'code')
md_cells = sum(1 for c in nb['cells'] if c['cell_type'] == 'markdown')
print(f"Total cells: {total}")
print(f"Code cells: {code_cells}")
print(f"Markdown cells: {md_cells}")
print(f"nbformat: {nb['nbformat']}")
print("Valid notebook!")
